name: Generate new release for plugin

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

env:
  PLUGIN_NAME: lkn-recurrency-give
  PHP_VERSION: "7.4"

jobs:
  release-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    # Run composer install and generate vendor
    - name: Run composer install
      uses: php-actions/composer@v6
      with:
        php_version: ${{ env.PHP_VERSION }}
        working_dir: "."
        args: --ignore-platform-reqs
        command: install
        dev: no

    # Add plugin files to a root directory
    - name: Prepare plugin folder
      run: |
        mkdir -p dist
        mkdir -p build/${PLUGIN_NAME}
        mv ./Admin ./Includes ./Languages ./Public *.php *.txt *.json ./build/${PLUGIN_NAME}/
        cp -r vendor build/${PLUGIN_NAME}/vendor
        find ./build/${PLUGIN_NAME} -type f -exec chmod 0644 {} +
        find ./build/${PLUGIN_NAME} -type d -exec chmod 0755 {} +

    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        path: 'build/${{ env.PLUGIN_NAME }}'
        directory: 'dist'
        filename: '${{ env.PLUGIN_NAME }}.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'

    # File upload to server via FTP
    - name: Upload .zip to server via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_HOST }} # Endereço do servidor FTP
        port: ${{ secrets.FTP_PORT }}
        username: ${{ secrets.FTP_USER }} # Usuário FTP
        password: ${{ secrets.FTP_PASSWORD }} # Senha FTP
        local-dir: ./dist # Diretório local onde o arquivo está
        server-dir: ./wp/ # Diretório remoto onde o arquivo será enviado
        #include: "${{ env.PLUGIN_NAME }}.zip" # Arquivo específico a ser enviado

    # File upload to server
    # - name: Upload .zip to server
    #   uses: easingthemes/ssh-deploy@main
    #   env:
    #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    #     ARGS: "-lptgoDz"
    #     SOURCE: ./${{ env.PLUGIN_NAME }}.zip
    #     EXCLUDE: "/.git, /.github, LICENSE.txt, README.md, README.txt, /${{ env.PLUGIN_NAME }}"
    #     REMOTE_HOST: ${{ secrets.SSH_HOST }}
    #     REMOTE_USER: ${{ secrets.SSH_USER }}
    #     TARGET: ${{secrets.DOWNLOAD_FOLDER}}${{ env.PLUGIN_NAME }}.zip

    # Update version tag
    # - name: Bump version and push tag
    #   id: tag_version
    #   uses: mathieudutour/github-tag-action@v6.0
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     custom_tag: '1.1.0' # // TODO caso necessário definir a tag da release manualmente

    # # Generate new release
    # - name: Generate new Release
    #   uses: ncipollo/release-action@v1
    #   with:
    #     artifacts: "${{ env.PLUGIN_NAME }}.zip"
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     commit: "main"
    #     draft: true
    #     tag: ${{ steps.tag_version.outputs.new_tag }}
    #     name: Release ${{ steps.tag_version.outputs.new_tag }}
