name: Generate new release for plugin

on:
  workflow_dispatch:

env:
  PLUGIN_NAME: lkn-recurrency-give
  PHP_VERSION: "7.4"

jobs:
  release-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    # Download encoded plugin
    - name: Download file
      run: "rm ${{ env.PLUGIN_NAME }}.zip && curl -o ${{ env.PLUGIN_NAME }}.zip -H \"Accept: application/zip\" '${{ secrets.DOWNLOAD_URL }}'"

    # Update version tag
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_tag: '1.1.0' # // TODO caso necessário definir a tag da release manualmente

    # Generate new release
    - name: Generate new Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/${{ env.PLUGIN_NAME }}.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        commit: "main"
        draft: true
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}